#ifndef __ECHATLIMITS_H__
#define __ECHATLIMITS_H__

#define TRUE 1
#define FALSE 0

#define MAX_NAME_LEN 32
#define MIN_NAME_LEN
#define MAX_PASSWORD_LEN 32
#define MIN_PASSWORD_LEN
#define MAX_GROUP_NAME_LEN 222
#define MIN_GROUP_NAME_LEN
#define MAX_IP_LEN 16
#define MAX_MESSAGE_LEN 259

#define MAX_GROUP_NUM 256
#define MAX_MEMBERS_IN_GROUP 1000

#endif /* __ECHATLIMITS_H__ */